import WebMCP from './WebMCP';

const layers = [
  { number:'01', label:'FOUNDATION', title:'Data & semantics', color:'lime', summary:'Give agents durable facts, portable records, and shared meaning.', items:[['Apache Arrow','In-memory columnar format','https://arrow.apache.org'],['Apache Parquet','Durable columnar files','https://parquet.apache.org'],['Apache Iceberg','Open table format','https://iceberg.apache.org'],['Apache Polaris','Catalog & governance','https://polaris.apache.org'],['Apache Ossie','Semantic metadata (Incubating)','https://ossie.apache.org']] },
  { number:'02', label:'INTELLIGENCE', title:'Models & routing', color:'cyan', summary:'Choose models by task, policy, economics, and deployment needs.', items:[['Open-weight models','Inspectable model artifacts','#'],['OpenRouter','Unified model routing','https://openrouter.ai'],['Nous Portal','Models, tools & cloud','https://portal.nousresearch.com'],['Local endpoints','Control at the boundary','#'],['Provider APIs','Capability without lock-in','#']] },
  { number:'03', label:'EXECUTION', title:'Harnesses & brokers', color:'amber', summary:'Turn intent into governed work with interchangeable runtimes.', items:[['OpenCode','Terminal coding agent','https://opencode.ai'],['Pi','Agent harness','https://github.com/earendil-works/pi'],['MagAgent','Developer agent framework','https://github.com/AlexMercedCoder/MagAgent'],['Loro','Governed agent harness','https://github.com/alexmerced-oss/loro'],['Merced AI','Agent broker','https://github.com/AlexMercedCoder/merced-ai'],['Hermes Agent','Evolving personal agent','https://github.com/NousResearch/hermes-agent'],['Prime Agent','Self-improving RLM agent','https://github.com/PrimeIntellect-ai/prime-agent']] },
  { number:'04', label:'INTEROPERABILITY', title:'Open standards', color:'pink', summary:'Make skills, context, profiles, and graphs portable across tools.', items:[['Agent Skills','Reusable capability folders','https://agentskills.io'],['MCP','Tools, data & workflow connection','https://modelcontextprotocol.io'],['OAP','Portable agent profiles','https://github.com/alexmerced-oss/open-agent-profile'],['AGS','Portable agentic graphs','https://github.com/AlexMercedCoder/agentic-graph-spec']] },
];

const tests = [
  ['Replaceable','Can one component be swapped without rebuilding the system?'],['Inspectable','Can a builder understand what runs and why?'],['Portable','Can identity, skills, context, and work move?'],['Bounded','Are authority and approval requirements explicit?'],['Grounded','Do agents share durable data and semantic meaning?'],['Auditable','Can people reconstruct decisions and outcomes?'],
];

export default function Home() {
  return <main>
    <WebMCP />
    <header className="topbar wrap"><a href="#top" className="logo"><span className="logo-grid"><i/><i/><i/><i/></span><b>OPEN AGENTIC<br/>PLATFORM</b></a><nav aria-label="Primary navigation"><a href="#stack">The stack</a><a href="#tests">Openness test</a><a href="#build">Build path</a><a className="spec-link" href="https://github.com/AlexMercedCoder/OpenAgenticPlatform">View source ↗</a></nav></header>

    <section className="hero wrap" id="top"><div className="hero-main"><p className="overline">A REFERENCE ARCHITECTURE FOR COMPOSABLE AI</p><h1>An open agentic<br/>platform is a <em>stack,</em><br/>not a suite.</h1><p className="intro">Build agentic systems from open data foundations, model choice, interchangeable harnesses, and portable standards—without surrendering the seams.</p><div className="hero-actions"><a href="#stack" className="action primary">EXPLORE THE STACK ↓</a><a href="#definition" className="action">READ THE DEFINITION →</a></div></div><div className="stack-visual" aria-label="Four layer open agentic platform architecture"><div className="visual-head"><span>REFERENCE STACK / 01</span><span>COMPOSABLE BY DESIGN</span></div>{layers.slice().reverse().map(layer=><div className={`visual-layer ${layer.color}`} key={layer.number}><span>{layer.number}</span><b>{layer.title}</b><small>{layer.items.length} OPEN COMPONENTS</small></div>)}<div className="visual-base"><span>YOUR POLICIES</span><span>YOUR INFRASTRUCTURE</span><span>YOUR CONTROL</span></div></div></section>

    <section className="definition" id="definition"><div className="wrap definition-grid"><p className="section-label">DEFINITION / 00</p><div><h2>Open components.<br/>Explicit contracts.<br/><em>Operational freedom.</em></h2><p>An open agentic platform is an architecture in which data, models, execution, and interoperability remain independently understandable and replaceable. “Open” may describe source, weights, formats, or interfaces. A trustworthy architecture labels the difference instead of flattening it.</p></div></div></section>

    <section className="stack wrap" id="stack"><div className="section-intro"><p className="section-label">ARCHITECTURE / 01–04</p><div><h2>Four layers.<br/>No mandatory vendor.</h2><p>Each layer answers a different question. Together they turn model capability into durable, governable work.</p></div></div><div className="layer-list">{layers.map(layer=><article className={`layer-card ${layer.color}`} key={layer.number}><div className="layer-title"><span>{layer.number} / {layer.label}</span><h3>{layer.title}</h3><p>{layer.summary}</p></div><div className="component-list">{layer.items.map(([name,role,href])=><a href={href} key={name}><b>{name}</b><span>{role}</span><i>↗</i></a>)}</div></article>)}</div></section>

    <section className="openness" id="tests"><div className="wrap"><div className="section-intro light"><p className="section-label">THE OPENNESS TEST / 05</p><div><h2>Open is a property<br/>of the whole system.</h2><p>A pile of open-source parts can still produce a closed architecture. Test the relationships as carefully as the licenses.</p></div></div><div className="test-grid">{tests.map(([title,body],index)=><article key={title}><span>{String(index+1).padStart(2,'0')}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>

    <section className="build wrap" id="build"><div className="section-intro"><p className="section-label">A PRACTICAL PATH / 06</p><div><h2>Build from the ground up.</h2><p>Start with durable context. Add intelligence and execution only after control boundaries are clear.</p></div></div><ol><li><span>1</span><div><b>Ground the system</b><p>Choose open formats, a catalog, and a semantic layer that agents and people can share.</p></div></li><li><span>2</span><div><b>Define the contracts</b><p>Express identity, skills, tools, workflows, policy, and approval points in portable forms.</p></div></li><li><span>3</span><div><b>Compose the runtime</b><p>Select models, routers, brokers, and harnesses according to the work—not brand gravity.</p></div></li><li><span>4</span><div><b>Observe and evolve</b><p>Retain evidence, evaluate outcomes, and replace components as requirements change.</p></div></li></ol></section>

    <section className="closing"><div className="wrap"><p className="section-label">THE PRINCIPLE</p><h2>Own the architecture.<br/><em>Keep the options.</em></h2><a href="https://github.com/AlexMercedCoder/OpenAgenticPlatform">FOLLOW THE PROJECT ON GITHUB ↗</a></div></section>
    <footer className="wrap"><a href="#top" className="logo"><span className="logo-grid"><i/><i/><i/><i/></span><b>OPEN AGENTIC<br/>PLATFORM</b></a><p>A vendor-neutral educational reference for open agentic architecture.</p><span>Community concepts; trademarks belong to their owners.<br/>© 2026</span></footer>
  </main>;
}
